version: "3.8"

services:
  postgres:
    container_name: nest-celan-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-celan
      PG_DATA: /data/postgres
    volumes:

      - ./data/pg:/data/postgres 